version: '3'
services:
  django:
    build: .
    ports:
     - "8000:8000"
    links:
      - postgres
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project
    #volumes:
    #  - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

