version: '3'
services:
  postgres:
    container_name: postgres
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project
    ports:
      - 5432:5432
    networks:
      - my-network

  djangoapp02:
    container_name: djangoapp02
    build: .
    networks:
      - my-network
    depends_on:
      - postgres
    ports:
      - 8080:8000

  nginx:
    container_name: nginx
    image: nginx:1.13
    ports:
      - 8004:8004
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - djangoapp02
    networks:
      - my-network

  angular:
    container_name: angular
    build: ./views
    networks:
      - my-network
    ports:
      - 80:80
networks:
  my-network:
